# Brevo REST API Configuration
brevo.api.key=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

# Sender Information
mail.from.address=ohshiny2006@gmail.com
mail.from.name=SkinAI
