/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.17
 * Generated at: 2026-06-10 03:07:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class public_002dfooter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1781059789271L));
    _jspx_dependants.put("jar:file:/C:/Users/Hoang%20Minh/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<!-- End Main Content -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* CSS hiệu ứng tương tác nâng cao cho Footer */\r\n");
      out.write("    .footer-link {\r\n");
      out.write("        color: #64748b;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-link:hover {\r\n");
      out.write("        color: #198754 !important; /* Màu xanh lá đặc trưng của SkinAI */\r\n");
      out.write("        transform: translateX(4px);\r\n");
      out.write("    }\r\n");
      out.write("    .social-icon {\r\n");
      out.write("        color: #64748b;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .social-icon:hover {\r\n");
      out.write("        color: #198754;\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("    }\r\n");
      out.write("    .disclaimer-box {\r\n");
      out.write("        border-left: 4px solid #ffc107;\r\n");
      out.write("        background-color: #fffbeb;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 1rem;\r\n");
      out.write("        transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .disclaimer-box:hover {\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"bg-white pt-5 pb-4 mt-5 border-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <!-- Column 1: Brand & Socials -->\r\n");
      out.write("            <div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("                <h3 class=\"fw-bold m-0\" style=\"color: #198754; font-family: 'Inter', sans-serif;\">\r\n");
      out.write("                    Skin<span class=\"text-dark\">AI</span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-muted mt-3 mb-4\" style=\"font-size: 0.9rem; line-height: 1.6;\">\r\n");
      out.write("                    An artificial intelligence platform supporting preliminary diagnosis of dermatological conditions through images. Fast, secure, and convenient.\r\n");
      out.write("                </p>\r\n");
      out.write("                <div class=\"d-flex gap-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"social-icon fs-4\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"social-icon fs-4\"><i class=\"fa-brands fa-twitter\"></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"social-icon fs-4\"><i class=\"fa-brands fa-linkedin\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Column 2: Quick Links -->\r\n");
      out.write("            <div class=\"col-12 col-md-4 mb-4 px-md-5\">\r\n");
      out.write("                <h5 class=\"fw-bold mb-4 text-dark\" style=\"font-size: 1.1rem; letter-spacing: -0.2px;\">Quick Links</h5>\r\n");
      out.write("                <ul class=\"list-unstyled m-0\">\r\n");
      out.write("                    <li class=\"mb-2\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\" class=\"footer-link\">\r\n");
      out.write("                            <i class=\"fa-solid fa-chevron-right me-1 small\" style=\"font-size: 0.7rem;\"></i> Home Page\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"mb-2\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/patient/diagnose\" class=\"footer-link\">\r\n");
      out.write("                            <i class=\"fa-solid fa-chevron-right me-1 small\" style=\"font-size: 0.7rem;\"></i> AI Diagnosis\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"mb-2\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/articles\" class=\"footer-link\">\r\n");
      out.write("                            <i class=\"fa-solid fa-chevron-right me-1 small\" style=\"font-size: 0.7rem;\"></i> Medical Knowledge\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"mb-2\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/clinics\" class=\"footer-link\">\r\n");
      out.write("                            <i class=\"fa-solid fa-chevron-right me-1 small\" style=\"font-size: 0.7rem;\"></i> Clinic Directory\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Column 3: Medical Disclaimer -->\r\n");
      out.write("            <div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("                <h5 class=\"fw-bold mb-4 text-warning d-flex align-items-center\" style=\"font-size: 1.1rem; letter-spacing: -0.2px;\">\r\n");
      out.write("                    <i class=\"fa-solid fa-triangle-exclamation me-2\"></i> Medical Disclaimer\r\n");
      out.write("                </h5>\r\n");
      out.write("                <div class=\"disclaimer-box text-muted small\">\r\n");
      out.write("                    The SkinAI system is for <strong>preliminary reference only</strong> based on computer vision algorithms. AI results <strong>cannot replace</strong> professional clinical diagnoses performed by a certified Dermatologist. Please consult a healthcare professional if you experience severe symptoms.\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <hr class=\"mt-4 mb-4 text-muted\" style=\"opacity: 0.1;\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"d-flex flex-column flex-sm-row justify-content-between align-items-center text-muted small gap-2\">\r\n");
      out.write("            <div>\r\n");
      out.write("                &copy; 2026 SkinAI Project - SWP391. All rights reserved.\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d-flex gap-3\">\r\n");
      out.write("                <a href=\"#\" class=\"text-muted text-decoration-none hover-primary\">Terms of Service</a>\r\n");
      out.write("                <span class=\"text-light-muted\">|</span>\r\n");
      out.write("                <a href=\"#\" class=\"text-muted text-decoration-none hover-primary\">Privacy Policy</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap 5 JS Bundle with Popper -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
