/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.17
 * Generated at: 2026-06-10 03:07:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class public_002dheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1781059789271L));
    _jspx_dependants.put("jar:file:/C:/Users/Hoang%20Minh/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SkinAI - AI Dermatology Diagnosis</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Fragment+Mono&family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap 5 CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- FontAwesome 6 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8fafc;\r\n");
      out.write("            font-family: 'Inter', system-ui, -apple-system, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- Custom Modern Navbar --- */\r\n");
      out.write("        .navbar-custom {\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            border-bottom: 1px solid #e2e8f0;\r\n");
      out.write("            padding-top: 0.8rem;\r\n");
      out.write("            padding-bottom: 0.8rem;\r\n");
      out.write("            transition: box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-custom:hover {\r\n");
      out.write("            box-shadow: 0 4px 20px rgba(0,0,0,0.02);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("            letter-spacing: -0.5px;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand:hover {\r\n");
      out.write("            transform: scale(1.02);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-custom .nav-link {\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #64748b;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("            padding: 0.5rem 1rem;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Hiệu ứng gạch chân trượt ra từ giữa khi Hover */\r\n");
      out.write("        .navbar-custom .nav-link::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 0;\r\n");
      out.write("            height: 2px;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            background-color: #198754; /* Màu xanh lá đồng bộ với logo */\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-custom .nav-link:hover::after, \r\n");
      out.write("        .navbar-custom .nav-link.active::after {\r\n");
      out.write("            width: 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-custom .nav-link:hover, .navbar-custom .nav-link.active {\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- Highlighted Back Button --- */\r\n");
      out.write("        .nav-link-highlight {\r\n");
      out.write("            font-size: 0.75rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #198754;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("            padding: 0.5rem 1rem;\r\n");
      out.write("            background-color: rgba(25, 135, 84, 0.1);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link-highlight:hover {\r\n");
      out.write("            background-color: rgba(25, 135, 84, 0.2);\r\n");
      out.write("            color: #146c43;\r\n");
      out.write("            transform: translateY(-1px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Profile Dropdown Minimalist */\r\n");
      out.write("        .profile-dropdown-toggle {\r\n");
      out.write("            color: #475569;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 0.5rem;\r\n");
      out.write("            transition: color 0.3s, transform 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-dropdown-toggle:hover {\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-dropdown-toggle:active {\r\n");
      out.write("            transform: scale(0.95);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hiệu ứng trượt mượt mà cho Dropdown */\r\n");
      out.write("        .dropdown-menu-custom {\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid #e2e8f0;\r\n");
      out.write("            box-shadow: 0 10px 25px -5px rgba(0,0,0,0.1);\r\n");
      out.write("            min-width: 200px;\r\n");
      out.write("            animation: slideDownFade 0.3s ease forwards;\r\n");
      out.write("            transform-origin: top center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes slideDownFade {\r\n");
      out.write("            from { opacity: 0; transform: translateY(-10px) scale(0.98); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0) scale(1); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-menu-custom .dropdown-item {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            padding: 0.6rem 1.2rem;\r\n");
      out.write("            color: #475569;\r\n");
      out.write("            transition: all 0.2s;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            margin: 0 0.3rem;\r\n");
      out.write("            width: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-menu-custom .dropdown-item:hover {\r\n");
      out.write("            background-color: #f1f5f9;\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("            transform: translateX(3px); /* Dịch chút nhẹ sang phải khi hover */\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Cải thiện Icon Logout */\r\n");
      out.write("        .dropdown-item.text-danger:hover {\r\n");
      out.write("            background-color: #fef2f2 !important;\r\n");
      out.write("            color: #dc2626 !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-skin {\r\n");
      out.write("            background-color: #198754;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-skin:hover {\r\n");
      out.write("            background-color: #146c43;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-custom sticky-top\">\r\n");
      out.write("    <div class=\"container-fluid px-4\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Left: Logo & Home Page Link -->\r\n");
      out.write("        <div class=\"d-flex align-items-center gap-4\">\r\n");
      out.write("            <a class=\"navbar-brand d-flex align-items-center fw-bold text-dark m-0\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">\r\n");
      out.write("                <i class=\"fa-solid fa-leaf text-success me-2 fs-4\"></i>\r\n");
      out.write("                <span class=\"fs-4\" style=\"font-family: 'Fragment Mono', sans-serif;\">Skin<span class=\"text-dark\">AI</span></span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile Toggle Button -->\r\n");
      out.write("        <button class=\"navbar-toggler border-0 shadow-none\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarContent\" aria-controls=\"navbarContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <i class=\"fa-solid fa-bars\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarContent\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- Center/Right: Navigation Links (ms-auto pushes it to the right) -->\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto align-items-lg-center\">\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item ms-lg-2\">\r\n");
      out.write("                    <a class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.requestURI.contains('home') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">Trang Chủ</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.requestURI.contains('diagnose') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/patient/diagnose\">Chẩn Đoán AI</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.requestURI.contains('articles') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/articles\">Bài Viết</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.requestURI.contains('clinics') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/clinics\">Phòng Khám</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!-- Vertical Divider (Desktop Only) -->\r\n");
      out.write("                <div class=\"vr mx-3 d-none d-lg-block\" style=\"opacity: 0.15; height: 24px; align-self: center;\"></div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Right: Profile Dropdown / Login -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Start Main Content -->\r\n");
      out.write("<main>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/layout/public-header.jsp(210,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.user}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"nav-item mt-3 mt-lg-0\">\r\n");
          out.write("                            <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/auth/login\" class=\"nav-link-highlight\">\r\n");
          out.write("                                <i class=\"fa-solid fa-right-to-bracket me-2\"></i> Đăng Nhập\r\n");
          out.write("                            </a>\r\n");
          out.write("                        </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"nav-item dropdown mt-3 mt-lg-0\">\r\n");
          out.write("                            <button class=\"nav-link profile-dropdown-toggle dropdown-toggle w-100 text-start\" type=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
          out.write("                                <i class=\"fa-regular fa-user me-1\"></i> \r\n");
          out.write("                                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.fullName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                            </button>\r\n");
          out.write("                            <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-custom mt-2 border-0 shadow-sm\">\r\n");
          out.write("                                ");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                <li>\r\n");
          out.write("                                    <a class=\"dropdown-item d-flex align-items-center\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/patient/profile\">\r\n");
          out.write("                                        <i class=\"fa-regular fa-id-badge fa-fw me-2 text-muted\"></i> Hồ Sơ\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                                <li>\r\n");
          out.write("                                    <a class=\"dropdown-item d-flex align-items-center\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/patient/appointments\">\r\n");
          out.write("                                        <i class=\"fa-regular fa-calendar-check fa-fw me-2 text-muted\"></i> Lịch Hẹn\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                                <li>\r\n");
          out.write("                                    <a class=\"dropdown-item d-flex align-items-center\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/patient/reports\">\r\n");
          out.write("                                        <i class=\"fa-solid fa-file-medical fa-fw me-2 text-muted\"></i> Hồ Sơ Bệnh Án\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                                <li><hr class=\"dropdown-divider\"></li>\r\n");
          out.write("                                <li>\r\n");
          out.write("                                    <form action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/auth/logout\" method=\"post\" class=\"m-0 p-0\">\r\n");
          out.write("                                        <button type=\"submit\" class=\"dropdown-item d-flex align-items-center text-danger w-100 bg-transparent border-0\">\r\n");
          out.write("                                            <i class=\"fa-solid fa-arrow-right-from-bracket fa-fw me-2\"></i> Đăng Xuất\r\n");
          out.write("                                        </button>\r\n");
          out.write("                                    </form>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            </ul>\r\n");
          out.write("                        </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/layout/public-header.jsp(224,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.role == 'ADMIN'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <li>\r\n");
          out.write("                                        <a class=\"dropdown-item d-flex align-items-center\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/dashboard\">\r\n");
          out.write("                                            <i class=\"fa-solid fa-chart-line fa-fw me-2 text-muted\"></i> Trang Quản Trị\r\n");
          out.write("                                        </a>\r\n");
          out.write("                                    </li>\r\n");
          out.write("                                    <li><hr class=\"dropdown-divider\"></li>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
