/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.17
 * Generated at: 2026-06-10 03:07:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.public_;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1781059789271L));
    _jspx_dependants.put("jar:file:/C:/Users/Hoang%20Minh/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/public-header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Banner -->\r\n");
      out.write("<section class=\"hero-section text-center d-flex align-items-center\" style=\"background: linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%); min-height: 500px;\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-8\">\r\n");
      out.write("                <h1 class=\"display-4 fw-bold mb-4\" style=\"color: var(--skin-primary); font-family: 'Fragment Mono', sans-serif;\">Chẩn đoán Da liễu AI</h1>\r\n");
      out.write("                <p class=\"lead mb-5 text-muted\" style=\"font-size: 1.25rem;\">Hệ thống phân tích hình ảnh sử dụng Trí tuệ Nhân tạo giúp phát hiện các bệnh lý về da trong vài giây, an toàn và chính xác.</p>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/patient/diagnose\" class=\"btn btn-skin btn-lg fw-bold px-5 py-3 shadow-sm\" style=\"font-size: 1.1rem;\">\r\n");
      out.write("                    Bắt đầu Chẩn đoán <i class=\"fa-solid fa-arrow-right ms-2\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Quy trình (How it works) -->\r\n");
      out.write("<section class=\"how-it-works py-5 bg-white\">\r\n");
      out.write("    <div class=\"container py-5\">\r\n");
      out.write("        <div class=\"text-center mb-5\">\r\n");
      out.write("            <h2 class=\"fw-bold mb-3\" style=\"color: var(--skin-primary); font-family: 'Fragment Mono', sans-serif;\">Cách Hoạt Động</h2>\r\n");
      out.write("            <p class=\"text-muted\">Đơn giản, Nhanh chóng và Hoàn toàn Bảo mật</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row text-center g-4\">\r\n");
      out.write("            <!-- Bước 1 -->\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"card h-100 p-4 border-0 shadow-sm rounded-4 hover-shadow transition\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"icon-wrapper mb-4 d-inline-flex align-items-center justify-content-center rounded-circle\" style=\"width: 80px; height: 80px; background-color: #eff6ff;\">\r\n");
      out.write("                            <i class=\"fa-solid fa-camera fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"fw-bold mb-3\" style=\"color: var(--skin-primary);\">1. Tải Ảnh Lên</h4>\r\n");
      out.write("                        <p class=\"text-muted small mb-0\">Chụp một bức ảnh rõ nét về tình trạng da của bạn bằng điện thoại hoặc máy ảnh.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Bước 2 -->\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"card h-100 p-4 border-0 shadow-sm rounded-4 hover-shadow transition\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"icon-wrapper mb-4 d-inline-flex align-items-center justify-content-center rounded-circle\" style=\"width: 80px; height: 80px; background-color: #eff6ff;\">\r\n");
      out.write("                            <i class=\"fa-solid fa-microchip fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"fw-bold mb-3\" style=\"color: var(--skin-primary);\">2. AI Phân Tích</h4>\r\n");
      out.write("                        <p class=\"text-muted small mb-0\">Hệ thống xử lý hình ảnh của bạn sử dụng mô hình Học Sâu tiên tiến.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Bước 3 -->\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"card h-100 p-4 border-0 shadow-sm rounded-4 hover-shadow transition\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"icon-wrapper mb-4 d-inline-flex align-items-center justify-content-center rounded-circle\" style=\"width: 80px; height: 80px; background-color: #eff6ff;\">\r\n");
      out.write("                            <i class=\"fa-solid fa-file-medical fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"fw-bold mb-3\" style=\"color: var(--skin-primary);\">3. Nhận Kết Quả</h4>\r\n");
      out.write("                        <p class=\"text-muted small mb-0\">Xem dự đoán bệnh lý, mức độ tự tin của AI và đánh giá mức độ rủi ro.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Bước 4 -->\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"card h-100 p-4 border-0 shadow-sm rounded-4 hover-shadow transition\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"icon-wrapper mb-4 d-inline-flex align-items-center justify-content-center rounded-circle\" style=\"width: 80px; height: 80px; background-color: #eff6ff;\">\r\n");
      out.write("                            <i class=\"fa-solid fa-hospital-user fa-2x text-primary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"fw-bold mb-3\" style=\"color: var(--skin-primary);\">4. Khám Chuyên Khoa</h4>\r\n");
      out.write("                        <p class=\"text-muted small mb-0\">Nhận đề xuất và đặt lịch khám tại các phòng khám da liễu gần nhất.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Call to action -->\r\n");
      out.write("<section class=\"cta-section py-5\" style=\"background-color: var(--skin-primary);\">\r\n");
      out.write("    <div class=\"container text-center py-4\">\r\n");
      out.write("        <h2 class=\"text-white fw-bold mb-4\">Bạn có vấn đề về da cần kiểm tra?</h2>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/patient/diagnose\" class=\"btn btn-light btn-lg rounded-pill px-5 fw-bold text-primary\">Tải Ảnh Lên Ngay</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .hover-shadow:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("        box-shadow: 0 15px 30px rgba(0,0,0,0.1) !important;\r\n");
      out.write("    }\r\n");
      out.write("    .transition {\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/public-footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
